services:
  web:
    build: .
    container_name: password-vault-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vault
      - SECRET_KEY=supersecretkey123456789012345678901234
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_MINUTES=1440
      - MIN_PASSWORD_LENGTH=16
      - MIN_USERNAME_LENGTH=6
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vault
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
